# Example Config to create a domain/dominion

port = 8000 # doesn't matter for the most part, the domain will find other domains on any functioning port

# All timings are in Nanoseconds
dialtimeout = 100000000	
domainCheck = 1000000000
serviceCheck = 5000000000


[services]
	[services.webServer]
		priority = "dependency" # this service will only be started if another service is running which requires it
		dependencies = []
		traits = [
			"compute",
		]
	[services.peripheralService]
		priority = "required" # if a domain has the traits this service needs it must be started
		dependencies = [
			"webServer", # this service requires a webService
		]
		traits = [
			"peripheral", # this service can only run on devices with peripheral
		]