# Example Config to create a domain/dominion
uuid = "GUID-1" # unique UUID

logfilepath = "/usr/local/dominion/logs/domain.log"

port = 9200 # doesn't matter for the most part, the domain will find other domains on any functioning port

traits = [
	# "compute", # TODO @jmbarzee consider changing to allow for types of compute
	"npLight",
]

# All timings are in Nanoseconds
dialtimeout = 100000000	
isolationCheck = 5000000000
serviceCheck = 1000000000
