# Example Config to create a domain/dominion
uuid = "<Insert Different Per Domain>" # TODO @user, insert the unique UUIDs here
title = "Dominion" # Should Be identical between domains

logfilename = "domain.log"

port = 9000 # doesn't matter for the most part, the domain will find other domains on any functioning port

traits = [
	"compute", # TODO @jmbarzee consider changing to allow for types of compute
	"lights",
]

[timingConfig]
	dialtimeout = 3000000	# All timings are in Nanoseconds
	[timingConfig.isolationCheck]
		upper = 10000000
		lower = 5000000
	[timingConfig.isolationTimeout]
		upper = 100000000
		lower = 50000000
	[timingConfig.heartbeatCheck]
		upper = 40000000
		lower = 10000000
	[timingConfig.serviceDependsCheck]
		upper = 10000000
		lower = 5000000

[services]
	[services.light]
		priority = "required"
		depends = [
			"lightFeed",
		]
		traits = [
			"lights",
		]
	[services.lightFeed]
		priority = "dependency"
		depends = [] # TODO @jmbarzee insert music-info after testing
		traits = [
			"compute",
		]
	[services.musicInfo]
		priority = "dependency"
		depends = []
		traits = [
			"compute",
		]

