# Example Config to create a domain/dominion


uuid = "<Insert Different Per Domain>" # TODO @user, insert the unique UUIDs here
title = "Dominion" # Should Be identical between domains

logfilename = "domain.log"

port = 9000 # doesn't matter for the most part, the domain will find other domains on any functioning port

traits = [
	"compute", # TODO @jmbarzee consider changing to allow for types of compute
	"lights",
]

[timingConfig]
	dialtimeout = 3000	# All timings are in Milliseconds
	[timingConfig.isolationCheck]
		upper = 1000
		lower = 500
	[timingConfig.isolationTimeout]
		upper = 10000
		lower = 9000
	[timingConfig.heartbeatCheck]
		upper = 2000
		lower = 1000

[services]
	[services.light]
		priority = "required"
		depends = [
			"lightFeed",
		]
		traits = [
			"lights",
		]
	[services.lightFeed]
		priority = "dependency"
		depends = [] # TODO @jmbarzee insert music-info after testing
		traits = [
			"compute",
		]
	[services.musicInfo]
		priority = "dependency"
		depends = []
		traits = [
			"compute",
		]

# domain specifies the traits of this instance (a part of the dominion)
[domain]

