# Example Config to create a domain/dominion

# dominion specifies the dependencies of the domain.
# this should be identical between domain instances.
factions:

  - name: light
    priority: always
    depends:
        - lightfeed
    traits:
        - lights

  - name: lightfeed
    priority: needed
    depends: []
    traits:
        - compute

# domain specifies the traits of this instance (a part of the dominion)
domain:
    logfilename: "domain.log"
    traits:
      - compute
      

# legion specifies the base communication of the distrubution of serives in the dominion
legion:
    title: Dominion
    port: 9000
    uuid: <Insert Different Per Legionnaire>
    dialtimeout: 3000    # In Milliseconds
    logfilename: "legionnaire.log"

